name: attendence
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localization: 
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  pdf: ^3.13.0
  printing: ^5.15.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # Yahan launcher icons package add kar diya gaya hai
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

# Icon ki configuration yahan set ki gayi hai
flutter_launcher_icons:
  image_path: "assets/images/app_icon.png"
  android: true
  ios: true